### PR TITLE
Join rewards doesn't enable rewards automatically for ads#1866

### LINKED ISSUE #1886: Join rewards doesn't enable rewards automatically for ads unsupported region
## Description 
Click on `Join rewards` from the onboarding flow doesn't automatically enable rewards if the device is not in a supported region

## Steps to reproduce 

   1. Keep device in an unsupported region for ads
   2. Clean install 1.20 and follow the onboarding flow
   3. Join rewards via onboarding flow, rewards doesn't enable automatically, need to manually enable it via rewards page

## Actual result 
Join rewards doesn't enable rewards automatically for ads unsupported region

## Expected result
Join rewards should automatically enable rewards irrespective of ads supported for a region or not

## Issue reproduces how often 
Easy

## Issue happens on 
   - Current Play Store version? N/A
   - Beta build? Yes

## Device details
   - Install type (ARM, x86): ARM
   - Device (Phone, Tablet, Phablet): Phone 
   - Android version: 8.1.0
   
## Brave version
1.20

### Website problems only
- Does the issue resolve itself when disabling Brave Shields? 
- Is the issue reproducible on the latest version of Chrome? 

### Additional information

cc: @anthonypkeane @EyanGoldman @deeppandya

### PR DESCRIPTION
**Pull request by gdregalo**
Closes #1886

### CODE REVIEW

File: chrome/android/java/src/org/chromium/chrome/browser/onboarding/BraveRewardsOnboardingFragment.java [hunk 1]
```diff
@@ -66,10 +68,25 @@
 
     private boolean fromSettings;
 
+    private BraveRewardsNativeWorker mBraveRewardsNativeWorker = BraveRewardsNativeWorker.getInstance();
+    private static final int WALLET_CREATED_OK = 12;
```
Comment (SergeyZhukovsky) [inline chrome/android/java/src/org/chromium/chrome/browser/onboarding/BraveRewardsOnboardingFragment.java]: Maybe let's define it in BraveRewardsNativeWorker for example and use the value from there in that class and in BraveRewardsPanelPopup. I'm just worry that if it ever changes in the future we will correct it in one place and miss another.
